---
title: "**Growth on PDA**"
author: "Jose Solorzano"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
grfungi <- read.csv("growthallassaypda.txt")
str(grfungi)
```

# Growth differences among fungi (PDA)
```{r include=FALSE}

#boxplot
colnames <- c("Aspergillus", "Ceratocystis", 
              "C. flagellaris", "C. janseana", "C. sojina",
              "C. zeae-maydis", "Colletotrichum", "Curvularia",
              "Exserohilum", "Macrophomina", "Magnaporthe", "Monilochaetes",
              "Rhizoctonia", "Rhizopus", "Sclerotium", "Xylaria")
boxplot(mean ~ fungi, 
        data = grfungi,
        ylab = "Growth (mm)",
        xlab = "Fungi",
        pars  =  list(xaxt = "n"))
axis(1, at=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15), 
     labels = FALSE)
text(c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15), 
     par("usr")[3] - 1.8, labels = colnames, srt = 30, pos = 1, xpd = TRUE,  adj = 0.965,)
```

# calculate mean and sd of each group

Get packages 
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#install.packages("tidyverse")
library("tidyverse")
library("ggplot2")
```
Get sd (make a function)
```{r include=FALSE}
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}
df3 <- data_summary(grfungi, varname="mean", 
                    groupnames=c("fungi", "day"))
head(df3)
```

Make a colorful graph
```{r include=FALSE}
ggplot(df3, aes(x=day, y=mean, group=fungi, color=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() + geom_point()+theme_minimal()
```
well...
\newpage

Lets do a subset of all of them
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
gr1 <-df3[which(df3$fungi %in% c("Xylaria", "Colletotricum")),]
gr2 <-df3[which(df3$fungi %in% c("Xylaria", "Cercospora_s")),]
gr3 <-df3[which(df3$fungi %in% c("Xylaria", "Rhizoctonia")),]
gr4 <-df3[which(df3$fungi %in% c("Xylaria", "Curvularia")),]
gr5 <-df3[which(df3$fungi %in% c("Xylaria", "Sclerotium")),]
gr6 <-df3[which(df3$fungi %in% c("Xylaria", "Exserohilum")),]
gr7 <-df3[which(df3$fungi %in% c("Xylaria", "Cercospora_f")),]
gr8 <-df3[which(df3$fungi %in% c("Xylaria", "Macrophomina")),]
gr9 <-df3[which(df3$fungi %in% c("Xylaria", "Ceratocystis")),]
gr10 <-df3[which(df3$fungi %in% c("Xylaria", "Magnaporthe")),]
gr11 <-df3[which(df3$fungi %in% c("Xylaria", "Rhizopus")),]
gr12 <-df3[which(df3$fungi %in% c("Xylaria", "Monilochaetes")),]
gr13 <-df3[which(df3$fungi %in% c("Xylaria", "Cercospora_z")),]
gr14 <-df3[which(df3$fungi %in% c("Xylaria", "Cercospora_j")),]
gr15 <-df3[which(df3$fungi %in% c("Xylaria", "Aspergillus")),]
```


Make the graphs
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#install.packages("mdthemes") #add italics
library("mdthemes")
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#1_comparison
p1 <- ggplot(gr1, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Colletotricum gloeosporioides*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#2_comparison
p2 <- ggplot(gr2, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Cercospora sojina*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#3_comparison
p3 <- ggplot(gr3, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Rhizoctonia solani*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#4_comparison
p4 <- ggplot(gr4, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Curvularia lunata*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#5_comparison
p5 <- ggplot(gr5, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Sclerotium rolfsii*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#6_comparison
p6 <- ggplot(gr6, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Exserohilum turcicum*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#7_comparison
p7 <- ggplot(gr7, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Cercospora flagellaris*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#8_comparison
p8 <- ggplot(gr8, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Macrophomina phaseolina*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#9_comparison
p9 <- ggplot(gr9, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Ceratocystis fimbriata*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#10_comparison
p10 <- ggplot(gr10, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Magnaporthe oryzae*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#11_comparison
p11 <- ggplot(gr11, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Rhizopus stolonifer*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#12_comparison
p12 <- ggplot(gr12, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Monilochaetes* sp.",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#13_comparison
p13 <- ggplot(gr13, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Cercospora zeae-maydis*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#14_comparison
p14 <- ggplot(gr14, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Cercospora janseana*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
#15_comparison
p15 <- ggplot(gr15, aes(x=day, y=mean, group=fungi, shape=fungi, linetype=fungi)) + 
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.1, 
                position=position_dodge(0.05)) +
  geom_line() +
  geom_point()+
  labs(title="X & *Aspergillus flavus*",x="Days", y = "Growth (mm)")+
  mdthemes::md_theme_classic()
```
\newpage

Group them?
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
#install.packages("ggpubr")
library("ggpubr")
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
group1 <- ggarrange(p1, p2, p3, p4, 
          labels = c("A.", "B.", "C.", "D."),
          ncol = 2, nrow = 2)
group2 <-  ggarrange(p5, p6, p7, p8, 
                     labels = c("E.", "F.", "G.", "H."),
                     ncol = 2, nrow = 2)
group3 <- ggarrange(p9, p10, p11, p12, 
          labels = c("I.", "J.", "K.", "L."),
          ncol = 2, nrow = 2)
group4 <- ggarrange(p13, p14, p15, 
                    labels = c("M.", "N.", "O."),
                    ncol = 2, nrow = 2)
```
\newpage
```{r}
group1
```
\newpage
```{r}
group2
```
\newpage
```{r}
group3
```
\newpage
```{r}
group4
```